# Sample deployment bosh 2.0 style manifest for
# depoying an HA vault
# Run deploy with --vars-store=vars.yml to auto-gen self-signed certs
# Must have a network and vm type called default
# in your cloud config, or modify the
name: vault

instance_groups:
- name: vault
  instances: 3
  vm_type: default
  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  persistent_disk: 10240

  jobs:
  - name: consul
    release: consul
    provides:
      consul_servers: { as: consul_leaders }
    consumes:
      consul_servers: { from: consul_leaders }

  - name: vault
    release: vault
    properties:
      vault:
        storage:
          use_consul: true
        listener:
          tcp:
            tls:
              certificate: ((vault-tls.certificate))
              key: ((vault-tls.private_key))
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000

variables:
- name: vault-ca
  type: certificate
  options:
    is_ca: true
    common_name: vaultCA
- name: vault-tls
  type: certificate
  options:
    ca: vault-ca
    common_name: vault

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

releases:
- name: consul
  version: 22.0.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/consul-boshrelease?v=22.0.0
  sha1: 1f8ed4e78213580933fe4ac39de0ff03cd609eb2
- name: vault
  version: 0.6.1
  url: https://bosh.io/d/github.com/cloudfoundry-community/vault-boshrelease?v=0.6.1
  sha1: 9f1bc371b5c1b7faadca97b892d6cc6d3c6baea6
