---
meta:
  name:   vault-boshrelease
  target: sw
  url:    https://ci.vsphere.starkandwayne.com

  initial_version: 0.2.1

  bosh-lite:
    target: https://10.58.111.44:25555

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   vault-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/vault-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/vault-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/vault-boshrelease/slack:webhook" ))
    channel: '#botspam'
