---
meta:
  name:    vault
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 0.2.1

  bosh-lite:
    target: https://10.58.111.49:25555
    username: (( vault "secret/bosh-lites/lite49/users/admin:username" ))
    password: (( vault "secret/bosh-lites/lite49/users/admin:password" ))
    cacert:   (( vault "secret/bosh-lites/lite49/certs:rootCA.pem" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   vault-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: (( vault "secret/pipelines/vault-boshrelease/slack:webhook" ))
    channel: '#vault'
    blob_success:  '(( concat "$BUILD_PIPELINE_NAME: New version of $BUILD_JOB_NAME was detected, and updated in master. <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME| Cut a new release?>" ))'
    blob_failure:  '(( concat "$BUILD_PIPELINE_NAME: :airplane_arriving: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed to update the blob for $BUILD_JOB_NAME>" ))'

resource_types:
- name: hashicorp-release
  type: docker-image
  source:
    repository: starkandwayne/hashicorp-release-resource

resources:
  - name: vault
    type: hashicorp-release
    source:
      project: vault

groups:
- name: blobs
  jobs:
  - vault

jobs:
- name: vault
  public: true
  plan:
  - aggregate:
    - { get: git }
    - { get: vault, trigger: true, params: { regexp: "linux_amd64" }}
  # - task: update-vault
  #   config:
  #     image_resource:
  #       type: docker-image
  #       source:
  #         repository: (( grab meta.image.name ))
  #         tag:        (( grab meta.image.tag ))
  #     platform: linux
  #     inputs:
  #     - name: git
  #     - name: vault
  #     outputs:
  #     - name: pushme
  #     run:
  #       path: ./git/ci/scripts/update-blob
  #     params:
  #       REPO_ROOT:   git
  #       REPO_OUT:    pushme
  #       BLOB_DIR:    vault
  #       BLOB_NAME:   vault
  #       BLOB_BINARY: vault_*_linux_amd64.zip
  #       BLOB_URL:    https://github.com/hashicorp/vault
  #       BLOB_CLEANUP:     vault/vault/vault_*_linux_amd64.zip
  #       BLOB_DESTINATION: vault/vault_${VERSION}_linux_amd64.zip
  #       AWS_ACCESS_KEY: (( grab meta.aws.access_key ))
  #       AWS_SECRET_KEY: (( grab meta.aws.secret_key ))
  #       BRANCH:         (( grab meta.github.branch ))
  #   on_failure:
  #     put: notify
  #     params:
  #       channel:  (( grab meta.slack.channel ))
  #       username: (( grab meta.slack.username ))
  #       icon_url: (( grab meta.slack.icon ))
  #       text:     (( grab meta.slack.blob_failure ))
  # - put: git
  #   params:
  #     rebase: true
  #     repository: pushme/git
    on_success:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.blob_success ))
    on_failure:
      put: notify
      params:
        channel:  (( grab meta.slack.channel ))
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:     (( grab meta.slack.blob_failure ))
